language: php
php:
  - 7.1
before_install:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer require tendoo/cms:dev-master
  - composer update
  - php artisan vendor:publish --tag=tendoo-config --force
  - php artisan vendor:publish --tag=tendoo-assets --force
  
script: "phpunit"
